import {
    Home as HomeIcon,
    School as SchoolIcon,
    Business as BusinessIcon,
    Work as WorkIcon,
  } from "@mui/icons-material"; // Import icons
const CategoryData = [
    { id: 1, name: "Education & Category", events: 12230, icon: <SchoolIcon /> },
    { id: 2, name: "Medical & Pharma", events: 2982, icon: <WorkIcon /> },
    { id: 3, name: "IT & Technology", events: 74782, icon: <BusinessIcon /> },
    { id: 4, name: "Banking and Finance", events: 12230, icon: <BusinessIcon /> },
    { id: 5, name: "Business Service", events: 28218, icon: <BusinessIcon /> },
    { id: 6, name: "Industrial Engineering", events: 12230, icon: <WorkIcon /> },
    { id: 7, name: "Entertainment & Media", events: 8283, icon: <HomeIcon /> },
    { id: 8, name: "Building & Construction", events: 12230, icon: <HomeIcon /> },
    { id: 9, name: "Science & Research", events: 7483, icon: <WorkIcon /> },
    {
      id: 10,
      name: "Wellness, Health & Wealth",
      events: 8578,
      icon: <HomeIcon />,
    },
    { id: 11, name: "Power & Energy", events: 12230, icon: <WorkIcon /> },
    { id: 12, name: "Arts & Crafts", events: 9843, icon: <HomeIcon /> },
    {
      id: 13,
      name: "Agriculture & Forestry",
      events: 8353,
      icon: <BusinessIcon />,
    },
    { id: 14, name: "Environment & Waste", events: 7645, icon: <WorkIcon /> },
    {
      id: 15,
      name: "Logistics & Transportation",
      events: 12230,
      icon: <BusinessIcon />,
    },
    { id: 16, name: "Electric & Electronics", events: 12230, icon: <WorkIcon /> },
    { id: 17, name: "Auto & Automotives", events: 12230, icon: <HomeIcon /> },
    { id: 18, name: "Fashion & Beauty", events: 12230, icon: <HomeIcon /> },
    { id: 19, name: "Home & Office", events: 12230, icon: <HomeIcon /> },
    { id: 20, name: "Travel & Tourism", events: 12230, icon: <HomeIcon /> },
    { id: 21, name: "Apparel & Clothing", events: 1238, icon: <HomeIcon /> },
    { id: 22, name: "Security & Defence", events: 9463, icon: <WorkIcon /> },
    { id: 23, name: "Telecommunication", events: 1284, icon: <WorkIcon /> },
    { id: 24, name: "Animal & Pets", events: 6743, icon: <HomeIcon /> },
    { id: 25, name: "Baby, Kids & Maternity", events: 4439, icon: <HomeIcon /> },
    { id: 26, name: "Hospitality", events: 9863, icon: <HomeIcon /> },
    { id: 27, name: "Packing & Packaging", events: 9834, icon: <HomeIcon /> },
    { id: 28, name: "Miscellaneous", events: 2342, icon: <HomeIcon /> },
    { id: 29, name: "Education & Category", events: 7864, icon: <SchoolIcon /> },
  ];

  export default CategoryData;